#include <ros/ros.h>
#include <std_msgs/Bool.h>
#include <string>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/opencv.hpp>
#include <opencv2/videoio.hpp>      
#include <opencv2/core.hpp>
#include <opencv2/imgproc/types_c.h>                                                                                                                        
#include <sensor_msgs/image_encodings.h>
#include <image_transport/image_transport.h>
#include <cv_bridge/cv_bridge.h>
#include <vector>
